# Generated by Django 3.2.23 on 2024-02-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_ordered',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='order_details',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
