# Generated by Django 3.2.23 on 2024-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240301_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order_details',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
