# Generated by Django 3.2.23 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240304_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
