# Generated by Django 3.2.23 on 2024-02-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional',
            field=models.TextField(null=True),
        ),
    ]
