# Generated by Django 3.2.23 on 2024-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240228_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='is_on_sale',
        ),
    ]
